apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "connection-hub-operator.fullname" . }}-controller-manager
  labels:
    app.kuberentes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: connection-hub-operator
    app.kubernetes.io/part-of: connection-hub-operator
  {{- include "connection-hub-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}