---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - connection-hub.roboscale.io
  resources:
  - submarinerbrokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - connection-hub.roboscale.io
  resources:
  - submarinerbrokers/finalizers
  verbs:
  - update
- apiGroups:
  - connection-hub.roboscale.io
  resources:
  - submarinerbrokers/status
  verbs:
  - get
  - patch
  - update
