# permissions for end users to view submarinerbrokers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: submarinerbroker-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: connection-hub-operator
    app.kubernetes.io/part-of: connection-hub-operator
    app.kubernetes.io/managed-by: kustomize
  name: submarinerbroker-viewer-role
rules:
- apiGroups:
  - connection-hub.roboscale.io
  resources:
  - submarinerbrokers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - connection-hub.roboscale.io
  resources:
  - submarinerbrokers/status
  verbs:
  - get
