apiVersion: connection-hub.roboscale.io/v1alpha1
kind: ConnectionHub
metadata:
  labels:
    app.kubernetes.io/name: connectionhub
    app.kubernetes.io/instance: connectionhub-sample
    app.kubernetes.io/part-of: connection-hub-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: connection-hub-operator
  name: connectionhub-sample
spec:
  # TODO(user): Add fields here
