apiVersion: connection-hub.roboscale.io/v1alpha1
kind: SubmarinerOperator
metadata:
  labels:
    app.kubernetes.io/name: submarineroperator
    app.kubernetes.io/instance: submarineroperator-sample
    app.kubernetes.io/part-of: connection-hub-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: connection-hub-operator
  name: submarineroperator-sample
spec:
  # TODO(user): Add fields here
