apiVersion: connection-hub.roboscale.io/v1alpha1
kind: ConnectionHub
metadata:
  labels:
    robolaunch.io/cloud-instance: <CLOUD-INSTANCE>
  name: connection-hub
spec:
  federationSpec:
    helmRepository:
        name: robolaunch
        url: <HELM-REPO-URL>
    helmChart:
      chartName: robolaunch/kubefed
      releaseName: kubefed
      version: 0.9.2
  instanceType: PhysicalInstance
  submarinerSpec:
    helmRepository:
      name: robolaunch
      url: <HELM-REPO-URL>
    brokerHelmChart:
      chartName: robolaunch/submariner-k8s-broker
      releaseName: submariner-k8s-broker
      version: 0.6.0
    operatorHelmChart:
      chartName: robolaunch/submariner-operator
      releaseName: submariner-operator
      version: 0.10.1
    apiServerURL: <CLOUD-INSTANCE-API-SERVER-URL>
    clusterCIDR: <CLOUD-INSTANCE-CLUSTER-CIDR
