{{- if eq .Values.instanceType "cloud" }}
apiVersion: connection-hub.roboscale.io/v1alpha1
kind: ConnectionHub
metadata:
  labels:
    robolaunch.io/cloud-instance: {{ .Values.cloudInstance }}
    robolaunch.io/cloud-instance-alias: {{ .Values.cloudInstanceAlias }}
  name: connection-hub
spec:
  federationSpec:
    helmRepository:
        name: robolaunch
        url: "http://charts.robolaunch.dev/robolaunch-helm-repository"
    helmChart:
      chartName: robolaunch/kubefed
      releaseName: kubefed
      version: 0.9.2
    controllerImage:
      repository: "robolaunchio"
      image: "kubefed"
      tag: "v0.9.2"
    webhookImage:
      repository: "robolaunchio"
      image: "kubefed"
      tag: "v0.9.2"
    postInstallJobImage:
      image: kubectl
      repository: robolaunchio
      tag: v1.24.10
    federatedTypes:
    - "namespaces"
    - "robots"
    - "buildmanagers"
    - "launchmanagers"
    - "robotartifacts"
    - "metricscollectors"
    - "fleet"
  submarinerSpec:
    helmRepository:
      name: submariner-latest
      url: "https://submariner-io.github.io/submariner-charts/charts"
    brokerHelmChart:
      chartName: submariner-latest/submariner-k8s-broker
      releaseName: submariner-k8s-broker
      version: ""
    operatorHelmChart:
      chartName: submariner-latest/submariner-operator
      releaseName: submariner-operator
      version: ""
    operatorImage:
      repository: "quay.io/submariner/submariner-operator"
      image: ""
      tag: "0.13.3"
    gatewayImage:
      repository: "quay.io/submariner/submariner-gateway"
      image: ""
      tag: "0.13.3"
    submarinerImages:
      repository: "quay.io/submariner"
      image: ""
      tag: "0.13.3"
    apiServerURL: {{ .Values.cloudInstanceAPIServerURL }}
    clusterCIDR: {{ .Values.clusterCIDR }}
    serviceCIDR: {{ .Values.serviceCIDR }}
{{ end }}