# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/submariner.io_submariners.yaml
- bases/submariner.io_brokers.yaml
- bases/submariner.io_servicediscoveries.yaml
- bases/core.kubefed.io_federatedtypeconfigs.yaml
- bases/core.kubefed.io_kubefedclusters.yaml
- bases/core.kubefed.io_kubefedconfigs.yaml
- bases/connection-hub.roboscale.io_submariners.yaml
- bases/connection-hub.roboscale.io_submarinerbrokers.yaml
- bases/connection-hub.roboscale.io_submarineroperators.yaml
- bases/connection-hub.roboscale.io_cloudinstances.yaml
- bases/connection-hub.roboscale.io_physicalinstances.yaml
- bases/connection-hub.roboscale.io_federationoperators.yaml
- bases/connection-hub.roboscale.io_federationhosts.yaml
- bases/connection-hub.roboscale.io_federationmembers.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_submariners.yaml
- patches/webhook_in_submarinerbrokers.yaml
- patches/webhook_in_submarineroperators.yaml
- patches/webhook_in_cloudinstances.yaml
#- patches/webhook_in_physicalinstances.yaml
#- patches/webhook_in_federationoperators.yaml
#- patches/webhook_in_federationhosts.yaml
#- patches/webhook_in_federationmembers.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_submariners.yaml
- patches/cainjection_in_submarinerbrokers.yaml
- patches/cainjection_in_submarineroperators.yaml
- patches/cainjection_in_cloudinstances.yaml
#- patches/cainjection_in_physicalinstances.yaml
#- patches/cainjection_in_federationoperators.yaml
#- patches/cainjection_in_federationhosts.yaml
#- patches/cainjection_in_federationmembers.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
